import { OverviewDashboardData } from './types';

export const mockOverviewData: OverviewDashboardData = {
  healthServices: [
    {
      id: 'srv-airflow',
      name: 'Airflow',
      status: 'healthy',
      statusLabel: 'Healthy',
      metric: '99.98%',
      metricLabel: 'Uptime SLA',
      iconName: 'Wind',
      latency: '24ms',
    },
    {
      id: 'srv-postgres',
      name: 'PostgreSQL',
      status: 'healthy',
      statusLabel: 'Healthy',
      metric: '12ms',
      metricLabel: 'Query Latency',
      iconName: 'Database',
      latency: '12ms',
    },
    {
      id: 'srv-kafka',
      name: 'Kafka',
      status: 'healthy',
      statusLabel: 'Healthy',
      metric: '1.2k msg/s',
      metricLabel: 'Throughput',
      iconName: 'Radio',
      latency: '8ms',
    },
    {
      id: 'srv-spark',
      name: 'Spark',
      status: 'healthy',
      statusLabel: 'Healthy',
      metric: '8 workers',
      metricLabel: 'Cluster Node Pool',
      iconName: 'Zap',
      latency: '14ms',
    },
    {
      id: 'srv-ai-agents',
      name: 'AI Agents',
      status: 'active',
      statusLabel: 'Active',
      metric: '5/5',
      metricLabel: 'Autonomous Units',
      iconName: 'Bot',
      latency: '180ms',
    },
  ],

  pipelineMetrics: [
    {
      id: 'metric-running',
      label: 'Running',
      value: 12,
      trend: '+4.2%',
      isPositive: true,
      description: 'Active streaming & batch tasks',
      statusType: 'running',
      iconName: 'PlayCircle',
    },
    {
      id: 'metric-successful',
      label: 'Successful',
      value: 284,
      trend: '+12.4%',
      isPositive: true,
      description: 'vs last 24h cycle',
      statusType: 'successful',
      iconName: 'CheckCircle2',
    },
    {
      id: 'metric-failed',
      label: 'Failed',
      value: 7,
      trend: '-18.2%',
      isPositive: true, // Decreasing failures is positive
      description: 'vs last 24h (-18.2% drop)',
      statusType: 'failed',
      iconName: 'XCircle',
    },
    {
      id: 'metric-queued',
      label: 'Queued',
      value: 4,
      trend: '+2.1%',
      isPositive: true,
      description: 'Awaiting executor slot',
      statusType: 'queued',
      iconName: 'Clock',
    },
  ],

  insights: [
    {
      id: 'insight-1',
      type: 'drift',
      severity: 'warning',
      title: 'Schema drift detected',
      message: 'customer_orders schema changed. 3 downstream pipelines affected.',
      affectedResources: ['customer_orders', 'dbt_orders_model', 'snowflake_sync'],
      actionLabel: 'Investigate',
      actionRoute: '/self-healing',
      timestamp: '14 mins ago',
    },
    {
      id: 'insight-2',
      type: 'optimization',
      severity: 'success',
      title: 'Pipeline optimization available',
      message: 'sales_daily_pipeline can be optimized by approximately 18% via partition pushdown.',
      affectedResources: ['sales_daily_pipeline'],
      actionLabel: 'Review',
      actionRoute: '/pipelines',
      timestamp: '32 mins ago',
    },
    {
      id: 'insight-3',
      type: 'lag',
      severity: 'warning',
      title: 'Kafka consumer lag increasing',
      message: 'fraud_stream_processor is approaching threshold (lag: 14.8k messages).',
      affectedResources: ['fraud_stream_processor', 'kafka_topic_transactions'],
      actionLabel: 'Diagnose',
      actionRoute: '/monitoring',
      timestamp: '1 hour ago',
    },
  ],

  engineeringCycle: [
    { step: 1, name: 'UNDERSTAND', description: 'Parse intent & requirements', status: 'completed', iconName: 'Brain', autonomousAgent: 'Requirements Agent' },
    { step: 2, name: 'PLAN', description: 'Decompose execution stages', status: 'completed', iconName: 'CalendarCheck', autonomousAgent: 'Planner Agent' },
    { step: 3, name: 'DESIGN', description: 'Synthesize schema & contracts', status: 'completed', iconName: 'Network', autonomousAgent: 'Architect Agent' },
    { step: 4, name: 'BUILD', description: 'Generate PySpark & Airflow DAGs', status: 'completed', iconName: 'Code', autonomousAgent: 'Builder Agent' },
    { step: 5, name: 'VALIDATE', description: 'Run contract tests & linters', status: 'completed', iconName: 'ShieldCheck', autonomousAgent: 'QA Agent' },
    { step: 6, name: 'DEPLOY', description: 'Zero-downtime CI/CD rollout', status: 'completed', iconName: 'Rocket', autonomousAgent: 'Deployer Agent' },
    { step: 7, name: 'MONITOR', description: 'Stream SLAs & query latencies', status: 'active', iconName: 'Activity', autonomousAgent: 'Telemetry Agent' },
    { step: 8, name: 'DETECT', description: 'Spot anomalies & schema drift', status: 'active', iconName: 'Eye', autonomousAgent: 'Watcher Agent' },
    { step: 9, name: 'DIAGNOSE', description: 'Root-cause stacktrace analysis', status: 'queued', iconName: 'Search', autonomousAgent: 'Diagnosis Agent' },
    { step: 10, name: 'REPAIR', description: 'Autonomous patch code diff', status: 'queued', iconName: 'Wrench', autonomousAgent: 'Healer Agent' },
    { step: 11, name: 'TEST', description: 'Run isolated sandbox replay', status: 'queued', iconName: 'TestTube', autonomousAgent: 'Replay Agent' },
    { step: 12, name: 'LEARN', description: 'Update RAG knowledge weights', status: 'queued', iconName: 'GraduationCap', autonomousAgent: 'Memory Agent' },
  ],

  recentActivities: [
    {
      id: 'act-1',
      time: '12:42',
      pipeline: 'sales_daily_pipeline',
      event: 'Completed',
      status: 'completed',
      duration: '4m 12s',
      recordsProcessed: '1.4M rows',
    },
    {
      id: 'act-2',
      time: '12:35',
      pipeline: 'customer_360_etl',
      event: 'Started',
      status: 'started',
      duration: '7m elapsed',
      recordsProcessed: '420K rows',
    },
    {
      id: 'act-3',
      time: '12:18',
      pipeline: 'fraud_stream_processor',
      event: 'Kafka lag',
      status: 'warning',
      duration: 'Ongoing',
      recordsProcessed: '14.8K lag',
    },
    {
      id: 'act-4',
      time: '11:56',
      pipeline: 'inventory_sync',
      event: 'Auto-healed',
      status: 'auto_healed',
      duration: '38s repair',
      recordsProcessed: '89K rows',
    },
    {
      id: 'act-5',
      time: '11:42',
      pipeline: 'sales_daily_pipeline',
      event: 'Schema updated',
      status: 'schema_updated',
      duration: 'Instant',
      recordsProcessed: '+1 column',
    },
  ],
};
