import { ConnectionProvider, DataConnection } from './types';

/* ------------------------------------------------------------------ */
/* Provider catalog — warehouses, databases, streaming, compute, cloud */
/* ------------------------------------------------------------------ */

export const PROVIDERS: ConnectionProvider[] = [
  {
    id: 'snowflake',
    name: 'Snowflake',
    category: 'warehouse',
    technology: 'Snowflake SQL API',
    description: 'Cloud data warehouse with virtual warehouses and Snowpipe Streaming.',
    authTypes: ['user_password', 'key_pair', 'oauth'],
    fields: [
      { key: 'account', label: 'Account Identifier', type: 'text', placeholder: 'acme.eu-central-1', required: true },
      { key: 'warehouse', label: 'Warehouse', type: 'text', placeholder: 'AIDEN_DEV_WH', required: true },
      { key: 'database', label: 'Database', type: 'text', placeholder: 'ANALYTICS_PROD', required: true },
      { key: 'username', label: 'Username', type: 'text', required: true },
      { key: 'password', label: 'Password', type: 'password', required: false, helper: 'Vault-managed when key-pair auth is used' },
    ],
  },
  {
    id: 'bigquery',
    name: 'BigQuery',
    category: 'warehouse',
    technology: 'Google BigQuery API',
    description: 'Serverless petabyte warehouse with streaming inserts and BI Engine.',
    authTypes: ['service_account', 'oauth'],
    fields: [
      { key: 'project_id', label: 'Project ID', type: 'text', placeholder: 'acme-prod-4281', required: true },
      { key: 'dataset', label: 'Default Dataset', type: 'text', placeholder: 'marts', required: false },
      { key: 'service_account_json', label: 'Service Account JSON', type: 'password', required: true },
    ],
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'database',
    technology: 'PostgreSQL wire protocol',
    description: 'OLTP source of truth with logical replication for CDC.',
    authTypes: ['user_password', 'iam_role'],
    defaultPort: 5432,
    fields: [
      { key: 'host', label: 'Host', type: 'text', placeholder: 'postgres-prod.acme.internal', required: true },
      { key: 'port', label: 'Port', type: 'number', placeholder: '5432', required: true },
      { key: 'database', label: 'Database', type: 'text', placeholder: 'ecommerce', required: true },
      { key: 'username', label: 'Username', type: 'text', required: true },
      { key: 'password', label: 'Password', type: 'password', required: true },
    ],
  },
  {
    id: 'mysql',
    name: 'MySQL',
    category: 'database',
    technology: 'MySQL wire protocol',
    description: 'Legacy OLTP systems and third-party application databases.',
    authTypes: ['user_password'],
    defaultPort: 3306,
    fields: [
      { key: 'host', label: 'Host', type: 'text', required: true },
      { key: 'port', label: 'Port', type: 'number', placeholder: '3306', required: true },
      { key: 'database', label: 'Database', type: 'text', required: true },
      { key: 'username', label: 'Username', type: 'text', required: true },
      { key: 'password', label: 'Password', type: 'password', required: true },
    ],
  },
  {
    id: 'kafka',
    name: 'Apache Kafka',
    category: 'streaming',
    technology: 'Kafka protocol (SASL/SSL)',
    description: 'Event streaming backbone for CDC and real-time analytics.',
    authTypes: ['sasl', 'user_password'],
    defaultPort: 9092,
    fields: [
      { key: 'bootstrap_servers', label: 'Bootstrap Servers', type: 'text', placeholder: 'kafka-prod.acme.internal:9092', required: true },
      { key: 'sasl_mechanism', label: 'SASL Mechanism', type: 'select', options: ['PLAIN', 'SCRAM-SHA-256', 'SCRAM-SHA-512'], required: true },
      { key: 'schema_registry_url', label: 'Schema Registry URL', type: 'text', placeholder: 'http://schema-registry:8081', required: false },
      { key: 'api_key', label: 'API Key', type: 'text', required: true },
      { key: 'api_secret', label: 'API Secret', type: 'password', required: true },
    ],
  },
  {
    id: 'spark',
    name: 'Apache Spark',
    category: 'compute',
    technology: 'Databricks / Spark Connect',
    description: 'Distributed compute for batch and streaming transformations.',
    authTypes: ['user_password', 'oauth'],
    fields: [
      { key: 'workspace_url', label: 'Workspace URL', type: 'text', placeholder: 'https://acme.cloud.databricks.com', required: true },
      { key: 'cluster_id', label: 'Cluster ID', type: 'text', placeholder: 'aiden-prod-cluster', required: true },
      { key: 'access_token', label: 'Access Token', type: 'password', required: true },
    ],
  },
  {
    id: 'airflow',
    name: 'Apache Airflow',
    category: 'compute',
    technology: 'Airflow REST API',
    description: 'Workflow orchestration for scheduling and backfills.',
    authTypes: ['user_password'],
    fields: [
      { key: 'base_url', label: 'Webserver URL', type: 'text', placeholder: 'https://airflow.acme.internal', required: true },
      { key: 'username', label: 'Username', type: 'text', required: true },
      { key: 'password', label: 'Password', type: 'password', required: true },
    ],
  },
  {
    id: 'aws',
    name: 'AWS S3',
    category: 'cloud',
    technology: 'AWS SDK (SigV4)',
    description: 'Data lake landing zones, Iceberg tables, and export staging.',
    authTypes: ['iam_role', 'user_password'],
    fields: [
      { key: 'bucket', label: 'Bucket', type: 'text', placeholder: 'acme-datalake-prod', required: true },
      { key: 'region', label: 'Region', type: 'select', options: ['eu-central-1', 'us-east-1', 'us-west-2', 'ap-south-1'], required: true },
      { key: 'role_arn', label: 'IAM Role ARN', type: 'text', placeholder: 'arn:aws:iam::123456789:role/aiden-access', required: false, helper: 'Leave empty to use access keys' },
      { key: 'access_key_id', label: 'Access Key ID', type: 'text', required: false },
      { key: 'secret_access_key', label: 'Secret Access Key', type: 'password', required: false },
    ],
  },
  {
    id: 'gcp',
    name: 'Google Cloud Storage',
    category: 'cloud',
    technology: 'GCS JSON API',
    description: 'Lakehouse object storage with uniform bucket-level access.',
    authTypes: ['service_account'],
    fields: [
      { key: 'bucket', label: 'Bucket', type: 'text', placeholder: 'acme-lakehouse-eu', required: true },
      { key: 'service_account_json', label: 'Service Account JSON', type: 'password', required: true },
    ],
  },
  {
    id: 'azure',
    name: 'Azure Data Lake',
    category: 'cloud',
    technology: 'ADLS Gen2 (ABFS)',
    description: 'Enterprise-grade lake storage with hierarchical namespaces.',
    authTypes: ['service_account', 'oauth'],
    fields: [
      { key: 'storage_account', label: 'Storage Account', type: 'text', placeholder: 'acmedatalake', required: true },
      { key: 'filesystem', label: 'Filesystem / Container', type: 'text', placeholder: 'raw', required: true },
      { key: 'tenant_id', label: 'Tenant ID', type: 'text', required: true },
      { key: 'client_id', label: 'Client ID', type: 'text', required: true },
      { key: 'client_secret', label: 'Client Secret', type: 'password', required: true },
    ],
  },
];

/* ------------------------------------------------------------------ */
/* Seeded connections                                                  */
/* ------------------------------------------------------------------ */

const now = new Date();
const iso = (minutesAgo: number) => new Date(now.getTime() - minutesAgo * 60000).toISOString();

export const SEED_CONNECTIONS: DataConnection[] = [
  {
    id: 'conn-snowflake-prod',
    name: 'Snowflake Analytics (Production)',
    providerId: 'snowflake',
    providerName: 'Snowflake',
    category: 'warehouse',
    environment: 'production',
    status: 'connected',
    host: 'acme.eu-central-1.snowflakecomputing.com',
    database: 'ANALYTICS_PROD',
    authType: 'key_pair',
    credentials: { account: 'acme.eu-central-1', warehouse: 'AIDEN_DEV_WH', username: 'AIDEN_SVC' },
    sslEnabled: true,
    createdAt: iso(60 * 24 * 120),
    lastCheckedAt: iso(2),
    latencyMs: 42,
    stats: { pipelinesUsing: 14, tablesIntrospected: 312, monthlyQueryCount: 184_300 },
  },
  {
    id: 'conn-pg-ecommerce',
    name: 'PostgreSQL Orders OLTP',
    providerId: 'postgresql',
    providerName: 'PostgreSQL',
    category: 'database',
    environment: 'production',
    status: 'connected',
    host: 'postgres-prod.acme.internal',
    port: 5432,
    database: 'ecommerce',
    authType: 'user_password',
    credentials: { host: 'postgres-prod.acme.internal', port: '5432', database: 'ecommerce', username: 'aiden_reader' },
    sslEnabled: true,
    createdAt: iso(60 * 24 * 200),
    lastCheckedAt: iso(1),
    latencyMs: 12,
    stats: { pipelinesUsing: 9, tablesIntrospected: 148, monthlyQueryCount: 96_100 },
  },
  {
    id: 'conn-kafka-prod',
    name: 'Kafka Event Backbone',
    providerId: 'kafka',
    providerName: 'Apache Kafka',
    category: 'streaming',
    environment: 'production',
    status: 'degraded',
    host: 'kafka-prod.acme.internal:9092',
    authType: 'sasl',
    credentials: { bootstrap_servers: 'kafka-prod.acme.internal:9092', sasl_mechanism: 'SCRAM-SHA-512' },
    sslEnabled: true,
    createdAt: iso(60 * 24 * 90),
    lastCheckedAt: iso(4),
    latencyMs: 87,
    stats: { pipelinesUsing: 6, tablesIntrospected: 23, monthlyQueryCount: 0 },
    lastError: 'Partition 3 on orders-cdc — consumer lag 12.8k (threshold 15k).',
  },
  {
    id: 'conn-airflow-dev',
    name: 'Airflow Orchestrator (Dev)',
    providerId: 'airflow',
    providerName: 'Apache Airflow',
    category: 'compute',
    environment: 'development',
    status: 'connected',
    host: 'airflow-dev.acme.internal',
    authType: 'user_password',
    credentials: { base_url: 'https://airflow-dev.acme.internal', username: 'aiden_bot' },
    sslEnabled: false,
    createdAt: iso(60 * 24 * 30),
    lastCheckedAt: iso(11),
    latencyMs: 64,
    stats: { pipelinesUsing: 21, tablesIntrospected: 0, monthlyQueryCount: 0 },
  },
  {
    id: 'conn-s3-lake',
    name: 'S3 Data Lake (EU)',
    providerId: 'aws',
    providerName: 'AWS S3',
    category: 'cloud',
    environment: 'production',
    status: 'connected',
    host: 's3.eu-central-1.amazonaws.com',
    authType: 'iam_role',
    credentials: { bucket: 'acme-datalake-prod', region: 'eu-central-1' },
    sslEnabled: true,
    createdAt: iso(60 * 24 * 150),
    lastCheckedAt: iso(3),
    latencyMs: 28,
    stats: { pipelinesUsing: 11, tablesIntrospected: 1204, monthlyQueryCount: 0 },
  },
  {
    id: 'conn-bq-marketing',
    name: 'BigQuery Marketing Sandbox',
    providerId: 'bigquery',
    providerName: 'BigQuery',
    category: 'warehouse',
    environment: 'staging',
    status: 'disconnected',
    host: 'bigquery.googleapis.com',
    authType: 'service_account',
    credentials: { project_id: 'acme-marketing-stg' },
    sslEnabled: true,
    createdAt: iso(60 * 24 * 10),
    lastCheckedAt: iso(60 * 26),
    latencyMs: null,
    stats: { pipelinesUsing: 0, tablesIntrospected: 0, monthlyQueryCount: 0 },
    lastError: 'Service account key expired — rotate credentials in the vault.',
  },
];
