import { PipelineConfig, GeneratedFile } from './types';

export const DEFAULT_PIPELINE_CONFIG: PipelineConfig = {
  pipelineName: 'orders_cdc_v1',
  executionMode: 'streaming',
  schedule: 'continuous',
  sourceSystem: 'PostgreSQL 15 — ecommerce.orders',
  targetSystem: 'Snowflake Enterprise — ANALYTICS_PROD.MART_ORDERS',
  writeStrategy: 'merge_upsert',
  batchSize: '5,000 records / 30s',
  retryPolicy: {
    maxRetries: 3,
    backoff: 'exponential',
    timeoutMinutes: 30,
  },
  qualityChecksEnabled: true,
  piiMaskingEnabled: true,
  alertingChannel: 'pagerduty',
  slaFreshnessMinutes: 15,
};

export const PIPELINE_NAME_REGEX = /^[a-z][a-z0-9_]{2,48}$/;

/* ------------------------------------------------------------------ */
/* Code generation templates                                           */
/* ------------------------------------------------------------------ */

export function buildPySparkCode(config: PipelineConfig, sources: string[], sinks: string[]): string {
  const source = sources[0] ?? 'postgres_prod.ecommerce.orders';
  const target = sinks[0] ?? 'ANALYTICS_PROD.MART_ORDERS';
  const maskingBlock = config.piiMaskingEnabled
    ? `
# --- PII Tokenization (GDPR / CCPA) ---
from pyspark.sql import functions as F

EMAIL_SALT = dbutils.secrets.get("aiden-vault", "pii-salt")
df = df.withColumn(
    "customer_email_hash",
    F.sha2(F.concat(F.col("customer_email"), F.lit(EMAIL_SALT)), 256),
).drop("customer_email")`
    : '';

  const dqBlock = config.qualityChecksEnabled
    ? `
# --- Quality Gate (Great Expectations) ---
from great_expectations.dataset import SparkDFDataset

ge_dataset = SparkDFDataset(df)
ge_dataset.expect_column_values_to_not_be_null("order_id")
ge_dataset.expect_column_values_to_be_unique("order_id")
ge_dataset.expect_column_values_to_meet_date_range("gross_amount_usd", 0.0, None)
violations = ge_dataset.validate()["statistics"]["unsuccessful_expectations"]
if violations > 0:
    raise ValueError(f"Quality gate failed with {violations} expectation violations — halting write.")`
    : '';

  return `"""
${config.pipelineName} — generated by AIDEN Pipeline Builder
Execution mode: ${config.executionMode}
Source: ${source}
Target: ${target}
Write strategy: ${config.writeStrategy}
SLA freshness: ${config.slaFreshnessMinutes} minutes
"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = (
    SparkSession.builder
    .appName("${config.pipelineName}")
    .config("spark.sql.shuffle.partitions", "64")
    .config("spark.streaming.backpressure.enabled", "true")
    .getOrCreate()
)

# --- Source Ingestion ---
df = (
    spark.read
    .format("jdbc")
    .option("url", "jdbc:postgresql://postgres-prod.acme.internal:5432/ecommerce")
    .option("dbtable", "public.orders")
    .option("user", dbutils.secrets.get("aiden-vault", "pg-user"))
    .option("password", dbutils.secrets.get("aiden-vault", "pg-password"))
    .load()
)
${maskingBlock}

# --- Transformations ---
df = (
    df
    .withColumnRenamed("id", "order_id")
    .withColumn("gross_amount_usd", F.col("gross_amount_cents") / 100.0)
    .withColumn("ingested_at", F.current_timestamp())
    .filter(F.col("status").isin("pending", "paid", "shipped", "delivered", "refunded"))
)
${dqBlock}

# --- Sink Write (${config.writeStrategy}) ---
MERGE_KEYS = ["order_id"]
TEMP_VIEW = "${config.pipelineName}_staging"
df.createOrReplaceTempView(TEMP_VIEW)

spark.sql(f"""
    MERGE INTO ${target} AS tgt
    USING {TEMP_VIEW} AS src
    ON tgt.order_id = src.order_id
    WHEN MATCHED THEN UPDATE SET *
    WHEN NOT MATCHED THEN INSERT *
""")

# --- Monitoring hooks ---
spark.streams.awaitAnyTermination()
`;
}

export function buildSqlCode(config: PipelineConfig, sinks: string[]): string {
  const target = sinks[0] ?? 'ANALYTICS_PROD.MART_ORDERS';

  return `-- ${config.pipelineName} — Snowflake MERGE generated by AIDEN
-- Write strategy: ${config.writeStrategy}

MERGE INTO ${target} AS tgt
USING (
    SELECT
        order_id,
        customer_id,
        gross_amount_usd,
        currency_code,
        order_status,
        order_timestamp,
        customer_email_hash,${config.piiMaskingEnabled ? '\n        -- PII masked upstream (SHA-256 salted)' : ''}
        ingested_at
    FROM ${config.pipelineName.toUpperCase()}_STAGING
    WHERE _dedupe_rank = 1  -- latest event per order_id
) AS src
ON tgt.order_id = src.order_id
WHEN MATCHED AND tgt.order_status <> src.order_status THEN UPDATE SET *
WHEN NOT MATCHED THEN INSERT *;${config.qualityChecksEnabled ? `

-- Post-write quality assertions (fail the task on violation)
ALTER TASK ${config.pipelineName}_qa RESUME;
CALL ASSERT_NO_DUPLICATES('${target}', 'order_id');
CALL ASSERT_FRESHNESS('${target}', 'order_timestamp', ${config.slaFreshnessMinutes});` : ''}
`;
}

export function buildAirflowDag(config: PipelineConfig): string {
  const schedule = config.schedule === 'continuous' ? None_DAG_SCHEDULE : `'@${config.schedule}'`;

  return `"""
${config.pipelineName} — Airflow DAG generated by AIDEN Pipeline Builder
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator

default_args = {
    "owner": "aiden",
    "retries": ${config.retryPolicy.maxRetries},
    "retry_delay": timedelta(minutes=1),
    "retry_exponential_backoff": ${config.retryPolicy.backoff === 'exponential' ? 'True' : 'False'},
    "execution_timeout": timedelta(minutes=${config.retryPolicy.timeoutMinutes}),
    "on_failure_callback": notify_${config.alertingChannel},
}

with DAG(
    dag_id="${config.pipelineName}",
    description="AIDEN generated ${config.executionMode} pipeline",
    schedule_interval=${schedule},
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["aiden", "${config.executionMode}"],
) as dag:

    submit_spark_job = DatabricksSubmitRunOperator(
        task_id="run_${config.pipelineName}",
        existing_cluster_id="aiden-prod-cluster",
        notebook_task={
            "notebook_path": "/Repos/PROD/pipelines/${config.pipelineName}",
        },
    )

    run_quality_gate = PythonOperator(
        task_id="quality_gate",
        python_callable=run_quality_checks,${config.qualityChecksEnabled ? '' : '\n        # disabled in pipeline configuration'}
    )

    submit_spark_job >> run_quality_gate
`;
}

// Helper referenced inside buildAirflowDag
const None_DAG_SCHEDULE = 'None  # event-driven / triggered by streaming job';

export function buildKafkaConfig(config: PipelineConfig): string {
  return `# ${config.pipelineName} — Kafka consumer configuration (AIDEN generated)
bootstrap.servers: kafka-prod.acme.internal:9092
group.id: ${config.pipelineName}-consumer
auto.offset.reset: earliest
enable.auto.commit: false
max.poll.records: ${config.executionMode === 'streaming' ? 500 : 5000}
fetch.max.bytes: 52428800
session.timeout.ms: 30000
heartbeat.interval.ms: 10000

# Reliability
isolation.level: read_committed
acks: all
retries: ${config.retryPolicy.maxRetries}
delivery.timeout.ms: 120000

# Schema registry for Avro/Protobuf deserialization
schema.registry.url: http://schema-registry.acme.internal:8081
specific.avro.reader: true
`;
}

export function buildTestSuite(config: PipelineConfig, sources: string[]): string {
  const source = sources[0] ?? 'ecommerce.orders';

  return `"""
${config.pipelineName} — pytest unit tests generated by AIDEN Pipeline Builder
Covers: schema conformance, PII masking, write strategy, idempotency.
"""

import pytest
import { PipelineConfig } from '../types';
import { GeneratedFile } from '../types';
from chispa import assert_df_equality
from pipelines.${config.pipelineName} import transform, apply_pii_masking


@pytest.fixture
def sample_orders(spark):
    return spark.createDataFrame(
        [
            ("ord-001", "cust-42", 12999, "paid"),
            ("ord-002", "cust-7", 0, "pending"),
        ],
        ["id", "customer_id", "gross_amount_cents", "status"],
    )


def test_schema_conformance(sample_orders):
    result = transform(sample_orders)
    expected_columns = {"order_id", "customer_id", "gross_amount_usd", "ingested_at"}
    assert expected_columns.issubset(set(result.columns))


def test_amount_conversion(sample_orders):
    result = transform(sample_orders)
    row = result.filter("order_id = 'ord-001'").first()
    assert row.gross_amount_usd == pytest.approx(129.99)
${config.piiMaskingEnabled ? `
def test_pii_email_is_masked(sample_orders):
    result = apply_pii_masking(sample_orders)
    assert "customer_email" not in result.columns
    assert "customer_email_hash" in result.columns` : ''}

def test_idempotent_merge(spark):
    """Replaying the same batch must not duplicate rows in ${source} target."""
    before = spark.sql(f"SELECT COUNT(*) FROM TARGET").first()[0]
    run_merge(batch_id=1)
    run_merge(batch_id=1)
    after = spark.sql(f"SELECT COUNT(*) FROM TARGET").first()[0]
    assert before + 1 == after
`;
}

export function buildAllFiles(config: PipelineConfig, sources: string[], sinks: string[]): GeneratedFile[] {
  const pyspark = buildPySparkCode(config, sources, sinks);
  const sql = buildSqlCode(config, sinks);
  const dag = buildAirflowDag(config);
  const kafka = buildKafkaConfig(config);
  const tests = buildTestSuite(config, sources);

  return [
    { target: 'pyspark', fileName: `${config.pipelineName}_job.py`, language: 'python', content: pyspark, lineCount: pyspark.split('\n').length },
    { target: 'sql', fileName: `${config.pipelineName}_merge.sql`, language: 'sql', content: sql, lineCount: sql.split('\n').length },
    { target: 'airflow_dag', fileName: `${config.pipelineName}_dag.py`, language: 'python', content: dag, lineCount: dag.split('\n').length },
    { target: 'kafka_config', fileName: `${config.pipelineName}_consumer.yaml`, language: 'yaml', content: kafka, lineCount: kafka.split('\n').length },
    { target: 'tests', fileName: `test_${config.pipelineName}.py`, language: 'python', content: tests, lineCount: tests.split('\n').length },
  ];
}
