"""
Multi-agent orchestrator for AIDEN using HuggingFace smolagents.

Uses a CodeAgent with specialized tools to build data pipelines:

    User Request
        │
        ▼
    ┌─────────────────────────────────────────────┐
    │  Orchestrator (CodeAgent with tools)        │
    │                                              │
    │  Phase 1: Schema discovery (DatabaseTool)    │
    │  Phase 2: Data profiling                     │
    │  Phase 3: Code generation (CodeGeneratorTool)│
    └─────────────────────────────────────────────┘
        │
        ▼
    Output: Airflow DAGs + dbt models + tests

Usage:
    from app.core.agent_orchestrator import AgentOrchestrator
    import asyncio

    orch = AgentOrchestrator()
    result = asyncio.run(orch.execute("Build a daily sales pipeline"))
"""

import json
import logging
from typing import Any, Dict, List, Optional

from smolagents import CodeAgent, Tool, ApiModel

from app.config import settings

logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════
#  Custom Tools
# ══════════════════════════════════════════════


class DatabaseTool(Tool):
    """Discover schemas and execute queries against data sources."""

    name = "database_tool"
    description = "Connects to a database to discover schemas or execute queries"
    inputs = {
        "action": {
            "type": "string",
            "description": "Action: 'schema' to discover tables/columns, 'query' to run SQL",
        },
        "connection_string": {
            "type": "string",
            "description": "Database connection string (e.g. postgresql://user:pass@host/db)",
        },
        "query": {
            "type": "string",
            "description": "SQL query to execute (required when action='query')",
            "nullable": True,
        },
    }
    output_type = "string"

    def forward(self, action: str, connection_string: str, query: str = None) -> str:
        # ── In production this would connect to the actual database ──
        if action == "schema":
            return (
                f"Schema discovery for {connection_string[:30]}...\n"
                "Tables: users, orders, products\n"
                "Columns (users): id, name, email, created_at"
            )
        elif action == "query":
            return f"Query executed ({len(query or '')} chars): {query[:80] if query else 'N/A'}"
        return f"Unknown action: {action}"


class CodeGeneratorTool(Tool):
    """Generate Airflow DAGs, dbt models, or data-quality test files."""

    name = "code_generator"
    description = (
        "Generates pipeline code: Airflow DAG, dbt model, or data quality tests"
    )
    inputs = {
        "spec": {
            "type": "string",
            "description": "Pipeline specification in JSON format",
        },
        "type": {
            "type": "string",
            "description": "Code type: 'dag', 'dbt', or 'test'",
        },
    }
    output_type = "string"

    def forward(self, spec: str, type: str = "dag") -> str:
        try:
            config = json.loads(spec) if isinstance(spec, str) else spec
        except json.JSONDecodeError:
            config = {"name": "pipeline"}

        name = config.get("name", "pipeline").replace(" ", "_").lower()
        source = config.get("source_type", "unknown")
        destination = config.get("destination_type", "unknown")
        schedule = config.get("schedule", "0 6 * * *")

        if type == "dag":
            return self._generate_dag(name, source, destination, schedule)
        elif type == "dbt":
            return self._generate_dbt(name, source, destination)
        elif type == "test":
            return self._generate_tests(name, config.get("transformations", []))
        return f"Unknown code type: {type}"

    @staticmethod
    def _generate_dag(name: str, source: str, dest: str, schedule: str) -> str:
        return f'''"""
DAG: {name}
Source: {source} → Destination: {dest}
Generated by AIDEN Agent Orchestrator
"""
from airflow import DAG
from airflow.operators.dummy import DummyOperator
from datetime import datetime, timedelta

default_args = {{
    "owner": "AIDEN",
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
}}

dag = DAG(
    "{name}",
    schedule_interval="{schedule}",
    default_args=default_args,
    catchup=False,
    tags=["AIDEN"],
)

start = DummyOperator(task_id="extract", dag=dag)
transform = DummyOperator(task_id="transform", dag=dag)
end = DummyOperator(task_id="load", dag=dag)

start >> transform >> end
'''

    @staticmethod
    def _generate_dbt(name: str, source: str, dest: str) -> str:
        return f"""-- dbt model: {name}
-- Source: {source} → Destination: {dest}

WITH source_data AS (
    SELECT * FROM {{{{ source('{source}', '{name}') }}}}
),

transformed AS (
    SELECT
        *,
        CURRENT_TIMESTAMP AS _loaded_at
    FROM source_data
)

SELECT * FROM transformed
"""

    @staticmethod
    def _generate_tests(name: str, transforms: List[str]) -> str:
        tests = []
        if "no_nulls" in transforms or "clean" in transforms:
            tests.append("  - name: test_not_null\n    condition: column IS NOT NULL")
        if "no_duplicates" in transforms:
            tests.append(
                "  - name: test_unique\n    condition: COUNT(*) = COUNT(DISTINCT column)"
            )
        if not tests:
            tests.append("  - name: test_not_null\n    condition: column IS NOT NULL")
        return (
            f"# Data quality tests for {name}\n"
            f"version: 2\n\nmodels:\n  - name: {name}\n    tests:\n{tests[0]}"
        )


# ══════════════════════════════════════════════
#  Agent Orchestrator
# ══════════════════════════════════════════════


class AgentOrchestrator:
    """
    Orchestrates data pipeline creation using smolagents CodeAgent.
    Uses a single CodeAgent equipped with specialized tools rather than
    managed sub-agents (the ManagedAgent API was removed in smolagents v1.0+).
    """

    def __init__(self):
        # Use API model (HuggingFace Inference API) with token
        self.model = ApiModel(
            model_id=settings.INTENT_MODEL,
            token=settings.HF_TOKEN,
        )

        # All available tools
        self.tools = [DatabaseTool(), CodeGeneratorTool()]
        self._agent = None

        logger.info("AgentOrchestrator initialized")

    # ── Public ──

    async def execute(
        self, task: str, context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Execute a data-pipeline task through the AI agent.

        Args:
            task: The user's natural language request.
            context: Optional additional context (parsed intent, etc.).

        Returns:
            Execution result with status, result, and tools_used.
        """
        logger.info("Orchestrator executing task: %s", task[:80])

        try:
            # Lazy-init the agent so module can be imported without triggering
            agent = self._get_agent()

            prompt = (
                f"Task: {task}\n"
                f"Context: {json.dumps(context or {})}\n\n"
                "Execute using available tools and return a summary."
            )

            result = agent.run(prompt)

            return {
                "status": "success",
                "result": str(result),
                "tools_used": [t.name for t in self.tools],
            }

        except Exception as exc:
            logger.error("Orchestration failed: %s", exc)
            return {"status": "failed", "error": str(exc)}

    # ── Private ──

    def _get_agent(self):
        """Create the CodeAgent on first use (lazy init)."""
        if self._agent is None:
            self._agent = CodeAgent(
                tools=self.tools,
                model=self.model,
                additional_authorized_imports=["json", "logging", "datetime"],
            )
        return self._agent
