"""
Standalone Code Generator — Pipeline Code Generation
=====================================================
Generates Airflow DAG, dbt models, and test configurations
from a parsed pipeline intent. No smolagents dependency.

This module is intentionally lightweight so it can be imported
quickly without triggering heavy ML library loads.
"""

import json
import logging
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


class CodeGenerator:
    """
    Generates pipeline code (Airflow DAG, dbt models, tests)
    from a parsed pipeline intent dict. Uses Jinja2-style string
    templates — no external dependencies, always fast to import.

    Usage:
        gen = CodeGenerator()
        dag_code = gen.generate_dag(intent_dict)
        dbt_code = gen.generate_dbt(intent_dict)
        test_config = gen.generate_tests(intent_dict)
    """

    def generate_dag(self, config: Dict[str, Any]) -> str:
        """
        Generate an Airflow DAG from a parsed pipeline config.

        Args:
            config: Pipeline configuration dict with keys:
                name, source_type, destination_type, schedule, transformations

        Returns:
            Airflow DAG Python code as a string
        """
        name = config.get("name", "pipeline").replace(" ", "_").lower()
        source = config.get("source_type", "unknown")
        destination = config.get("destination_type", "unknown")
        schedule = config.get("schedule", "0 6 * * *")
        transforms = config.get("transformations", [])
        transforms_str = ", ".join(transforms) if transforms else "None"

        return f'''"""
AIDEN Auto-Generated Pipeline: {name}
Source: {source}
Destination: {destination}
Schedule: {schedule}
Transformations: {transforms_str}
"""

from airflow import DAG
from datetime import datetime, timedelta
from airflow.operators.python import PythonOperator
from airflow.operators.dummy import DummyOperator

default_args = {{
    "owner": "AIDEN",
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
    "start_date": datetime(2024, 1, 1),
}}

dag = DAG(
    "{name}",
    schedule_interval="{schedule}",
    default_args=default_args,
    catchup=False,
    description="Auto-generated pipeline: {name} (source: {source}, dest: {destination})",
)

def extract():
    """Extract data from {source}."""
    import logging
    logger = logging.getLogger(__name__)
    logger.info("Extracting data from {source}...")
    # TODO: Implement {source} extraction logic
    return [{{"id": 1, "data": "sample"}}]

def transform(**context):
    """Apply {transforms_str} transformations."""
    import logging
    logger = logging.getLogger(__name__)
    ti = context["ti"]
    data = ti.xcom_pull(task_ids="extract")
    logger.info("Applying transformations: {transforms_str}")
    # TODO: Implement transformation logic
    return data

def load(**context):
    """Load data into {destination}."""
    import logging
    logger = logging.getLogger(__name__)
    ti = context["ti"]
    data = ti.xcom_pull(task_ids="transform")
    logger.info("Loading data into {destination}...")
    # TODO: Implement {destination} load logic
    return "loaded"

start = DummyOperator(task_id="start", dag=dag)
extract_task = PythonOperator(
    task_id="extract",
    python_callable=extract,
    dag=dag,
)
transform_task = PythonOperator(
    task_id="transform",
    python_callable=transform,
    dag=dag,
)
load_task = PythonOperator(
    task_id="load",
    python_callable=load,
    dag=dag,
)
end = DummyOperator(task_id="end", dag=dag)

start >> extract_task >> transform_task >> load_task >> end
'''

    def generate_dbt(self, config: Dict[str, Any]) -> str:
        """
        Generate a dbt model from a parsed pipeline config.

        Args:
            config: Pipeline configuration dict

        Returns:
            dbt SQL model as a string
        """
        name = config.get("name", "pipeline").replace(" ", "_").lower()
        source = config.get("source_type", "unknown")
        transforms = config.get("transformations", [])

        transforms_sql = ""
        if transforms:
            transforms_sql = ",\\n        ".join(
                [f"    -- TODO: implement {t}" for t in transforms]
            )
            transforms_sql = "\\n        " + transforms_sql

        return f'''-- dbt model: {name}
-- source: {source}
-- auto-generated by AIDEN

{{{{ config(materialized='table') }}}}

SELECT
    *{transforms_sql}
FROM {{{{ source('{source}', '{name}') }}}}
WHERE 1=1
'''

    def generate_tests(self, config: Dict[str, Any]) -> list:
        """
        Generate data quality test definitions.

        Args:
            config: Pipeline configuration dict

        Returns:
            List of test configuration dicts
        """
        rules = config.get("data_quality_rules", [])
        tests = []

        if not rules:
            # Default tests
            tests.append({
                "name": "test_not_null",
                "type": "not_null",
                "column": "id",
                "description": "Primary key should not be null",
            })
            tests.append({
                "name": "test_row_count",
                "type": "row_count",
                "min_rows": 1,
                "description": "Table should have at least 1 row",
            })
        else:
            for rule in rules:
                test_name = f"test_{rule.replace(' ', '_')}"
                tests.append({
                    "name": test_name,
                    "type": "generic",
                    "description": rule,
                })

        return tests

    def generate_all(self, config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate all pipeline code (DAG + dbt + tests).

        Args:
            config: Pipeline configuration dict

        Returns:
            Dict with keys: dag_code, dbt_code, tests
        """
        return {
            "dag_code": self.generate_dag(config),
            "dbt_code": self.generate_dbt(config),
            "tests": self.generate_tests(config),
            "summary": f"Generated DAG + dbt + {len(config.get('data_quality_rules') or []) or 1} test(s)",
        }


# Convenience singleton (optional — users can also instantiate directly)
code_generator = CodeGenerator()
