"""
Self-Healing Engine — Automatic Failure Diagnosis & Recovery
============================================================

Detects pipeline execution failures, diagnoses root causes,
proposes fixes, assesses risk, and drives the approval workflow.

Architecture:

    ┌────────────────────────────────────────────────────────────────┐
    │  SelfHealingEngine                                            │
    │                                                                │
    │  1. FAILURE DETECTION                                          │
    │     └── Error message pattern matching                         │
    │                                                                │
    │  2. ROOT CAUSE ANALYSIS                                        │
    │     ├── Schema Drift   — column(s) added/renamed/dropped       │
    │     ├── Data Quality   — nulls, duplicates, format issues      │
    │     ├── Performance    — timeouts, resource exhaustion         │
    │     ├── Connection     — database/API unreachable              │
    │     └── Code Error     — syntax, logic bugs in generated DAG   │
    │                                                                │
    │  3. FIX PROPOSAL (rule-based + optional LLM)                   │
    │     └── Generates a structured fix for the diagnosed problem   │
    │                                                                │
    │  4. RISK ASSESSMENT                                            │
    │     ├── LOW       — Auto-apply, no approval needed             │
    │     ├── MEDIUM    — Suggest fix, auto-approve after 5 min      │
    │     ├── HIGH      — Create approval, human must approve        │
    │     └── CRITICAL  — Create approval, page on-call              │
    │                                                                │
    │  5. FIX APPLICATION                                            │
    │     └── Apply fix → Update pipeline config → Re-run           │
    │                                                                │
    │  6. LEARNING                                                    │
    │     └── Store fix + outcome in RAG memory for future           │
    └────────────────────────────────────────────────────────────────┘
"""

import asyncio
import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

from app.api.v1.websocket import manager
from app.core.rag_memory import rag_memory
from app.services.hf_service import hf_service
from app.models.approval import Approval, ApprovalAction, ApprovalStatus, RiskLevel
from app.models.pipeline import Pipeline, PipelineStatus
from app.models.execution import PipelineExecution, ExecutionStatus
from app.models.user import User
from app.database import AsyncSessionLocal

logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════════════════
# Data Types
# ══════════════════════════════════════════════════════════════════════════


class FailureCategory(str, Enum):
    """High-level categories that the RCA maps errors into."""

    SCHEMA_DRIFT = "schema_drift"
    DATA_QUALITY = "data_quality"
    PERFORMANCE = "performance"
    CONNECTION = "connection"
    CODE_ERROR = "code_error"
    UNKNOWN = "unknown"


@dataclass
class HealingDiagnosis:
    """Result of the root-cause analysis step."""

    category: FailureCategory
    summary: str                         # Human-readable one-liner
    detail: str                          # Longer technical explanation
    confidence: float                    # 0.0 – 1.0
    error_snippet: str                   # The error text that was matched
    affected_columns: List[str] = field(default_factory=list)
    source_tables: List[str] = field(default_factory=list)


@dataclass
class HealingFix:
    """A proposed fix generated by the engine."""

    action: str                          # e.g. "update_query", "retry_with_backoff"
    description: str                     # Human-readable description of the fix
    config_patch: Optional[Dict[str, Any]] = None  # Partial pipeline.config update
    code_patch: Optional[str] = None     # Partial DAG/code replacement
    message: str = ""                    # Log-friendly detail

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action": self.action,
            "description": self.description,
            "config_patch": self.config_patch,
            "code_patch": self.code_patch,
            "message": self.message,
        }


@dataclass
class HealingResult:
    """Complete result returned by :meth:`SelfHealingEngine.diagnose_and_heal`."""

    diagnosis: HealingDiagnosis
    fix: Optional[HealingFix] = None
    risk: RiskLevel = RiskLevel.LOW
    approval_id: Optional[int] = None    # Set if an approval record was created
    auto_applied: bool = False           # True when LOW-risk fix was applied
    error: Optional[str] = None          # Set if the engine itself failed


# ══════════════════════════════════════════════════════════════════════════
# Failure Pattern Database
# ══════════════════════════════════════════════════════════════════════════


# Each entry: (regex_pattern, category, summary_template, action)
FAILURE_PATTERNS: List[Tuple[re.Pattern, FailureCategory, str, str]] = [
    # ── Schema Drift ────────────────────────────────────────────────
    (
        re.compile(r"column .* does not exist", re.IGNORECASE),
        FailureCategory.SCHEMA_DRIFT,
        "Column referenced in query no longer exists in source table",
        "update_query",
    ),
    (
        re.compile(r"no such column", re.IGNORECASE),
        FailureCategory.SCHEMA_DRIFT,
        "SQL column not found — likely renamed or dropped",
        "update_query",
    ),
    (
        re.compile(r"table .* does not exist", re.IGNORECASE),
        FailureCategory.SCHEMA_DRIFT,
        "Source or destination table not found",
        "update_query",
    ),
    (
        re.compile(r"relation .* does not exist", re.IGNORECASE),
        FailureCategory.SCHEMA_DRIFT,
        "PostgreSQL relation (table/view) not found",
        "update_query",
    ),
    (
        re.compile(r"ambiguous column", re.IGNORECASE),
        FailureCategory.SCHEMA_DRIFT,
        "Ambiguous column reference — multiple tables share the same column name",
        "update_query",
    ),
    # ── Data Quality ────────────────────────────────────────────────
    (
        re.compile(r"null value .* violates not-null", re.IGNORECASE),
        FailureCategory.DATA_QUALITY,
        "NOT NULL constraint violated by null data",
        "add_null_handling",
    ),
    (
        re.compile(r"duplicate key value violates unique constraint", re.IGNORECASE),
        FailureCategory.DATA_QUALITY,
        "Duplicate values violate unique constraint",
        "add_dedup",
    ),
    (
        re.compile(r"check constraint", re.IGNORECASE),
        FailureCategory.DATA_QUALITY,
        "CHECK constraint failed — data out of allowed range",
        "add_validation",
    ),
    (
        re.compile(r"value too long for type", re.IGNORECASE),
        FailureCategory.DATA_QUALITY,
        "String value exceeds column length limit",
        "add_truncation",
    ),
    (
        re.compile(r"invalid input syntax for type", re.IGNORECASE),
        FailureCategory.DATA_QUALITY,
        "Type-cast failure — value doesn't match target column type",
        "add_type_cast",
    ),
    (
        re.compile(r"division by zero", re.IGNORECASE),
        FailureCategory.DATA_QUALITY,
        "Division by zero in transformation logic",
        "add_zero_guard",
    ),
    # ── Performance ─────────────────────────────────────────────────
    (
        re.compile(r"timeout", re.IGNORECASE),
        FailureCategory.PERFORMANCE,
        "Operation timed out — consider increasing timeout or optimising query",
        "increase_timeout",
    ),
    (
        re.compile(r"out of memory", re.IGNORECASE),
        FailureCategory.PERFORMANCE,
        "Out of memory — reduce batch size or add resource limits",
        "reduce_batch_size",
    ),
    (
        re.compile(r"disk full", re.IGNORECASE),
        FailureCategory.PERFORMANCE,
        "Disk full — free storage or increase volume size",
        "increase_storage",
    ),
    (
        re.compile(r"too many connections", re.IGNORECASE),
        FailureCategory.PERFORMANCE,
        "Too many database connections — reduce pool size or close idle connections",
        "reduce_pool_size",
    ),
    (
        re.compile(r"deadlock detected", re.IGNORECASE),
        FailureCategory.PERFORMANCE,
        "Database deadlock — retry with exponential backoff",
        "retry_with_backoff",
    ),
    (
        re.compile(r"query .* took too long", re.IGNORECASE),
        FailureCategory.PERFORMANCE,
        "Query execution exceeded time limit",
        "optimise_query",
    ),
    # ── Connection ──────────────────────────────────────────────────
    (
        re.compile(r"connection refused", re.IGNORECASE),
        FailureCategory.CONNECTION,
        "Database or service refused the connection",
        "retry_with_backoff",
    ),
    (
        re.compile(r"could not connect", re.IGNORECASE),
        FailureCategory.CONNECTION,
        "Could not reach the remote service",
        "retry_with_backoff",
    ),
    (
        re.compile(r"network unreachable", re.IGNORECASE),
        FailureCategory.CONNECTION,
        "Network is unreachable",
        "retry_with_backoff",
    ),
    (
        re.compile(r"name or service not known", re.IGNORECASE),
        FailureCategory.CONNECTION,
        "DNS resolution failed — hostname not found",
        "retry_with_backoff",
    ),
    (
        re.compile(r"authentication failed", re.IGNORECASE),
        FailureCategory.CONNECTION,
        "Authentication credentials rejected",
        "update_credentials",
    ),
    (
        re.compile(r"password authentication failed", re.IGNORECASE),
        FailureCategory.CONNECTION,
        "Database password is incorrect",
        "update_credentials",
    ),
    (
        re.compile(r"permission denied", re.IGNORECASE),
        FailureCategory.CONNECTION,
        "Insufficient permissions for the requested operation",
        "check_permissions",
    ),
    (
        re.compile(r"SSL connection error", re.IGNORECASE),
        FailureCategory.CONNECTION,
        "SSL/TLS handshake failed",
        "update_connection_config",
    ),
    (
        re.compile(r"broken pipe", re.IGNORECASE),
        FailureCategory.CONNECTION,
        "Connection lost — server closed the connection unexpectedly",
        "retry_with_backoff",
    ),
    # ── Code Error ──────────────────────────────────────────────────
    (
        re.compile(r"NameError", re.IGNORECASE),
        FailureCategory.CODE_ERROR,
        "Undefined variable in generated code",
        "fix_code_error",
    ),
    (
        re.compile(r"SyntaxError", re.IGNORECASE),
        FailureCategory.CODE_ERROR,
        "Syntax error in generated DAG or transformation code",
        "fix_code_error",
    ),
    (
        re.compile(r"TypeError", re.IGNORECASE),
        FailureCategory.CODE_ERROR,
        "Type mismatch in generated code",
        "fix_code_error",
    ),
    (
        re.compile(r"AttributeError", re.IGNORECASE),
        FailureCategory.CODE_ERROR,
        "Attribute reference error in generated code",
        "fix_code_error",
    ),
    (
        re.compile(r"KeyError", re.IGNORECASE),
        FailureCategory.CODE_ERROR,
        "Missing dictionary key in generated code",
        "fix_code_error",
    ),
    (
        re.compile(r"ImportError|ModuleNotFoundError", re.IGNORECASE),
        FailureCategory.CODE_ERROR,
        "Missing import in generated code",
        "fix_code_error",
    ),
    (
        re.compile(r"IndexError|list index out of range", re.IGNORECASE),
        FailureCategory.CODE_ERROR,
        "List index out of range in generated code",
        "fix_code_error",
    ),
    (
        re.compile(r"JSONDecodeError|json\.decode", re.IGNORECASE),
        FailureCategory.CODE_ERROR,
        "Failed to parse JSON configuration",
        "fix_code_error",
    ),
]


# ══════════════════════════════════════════════════════════════════════════
# Self-Healing Engine
# ══════════════════════════════════════════════════════════════════════════


class SelfHealingEngine:
    """
    Diagnoses pipeline execution failures and drives the fix + approval
    workflow automatically.

    Usage::

        engine = SelfHealingEngine()
        result = await engine.diagnose_and_heal(pipeline, execution)
        if result.auto_applied:
            logger.info("Fix auto-applied, re-running pipeline")
        elif result.approval_id:
            logger.info("Fix requires approval #%s", result.approval_id)
    """

    # ── Public API ─────────────────────────────────────────────────────

    async def diagnose_and_heal(
        self,
        pipeline: Pipeline,
        execution: PipelineExecution,
        error: str,
    ) -> HealingResult:
        """
        Analyse a failed execution, propose a fix, assess risk, and drive
        the approval or auto-apply workflow.

        Args:
            pipeline: The pipeline that failed.
            execution: The failed execution record.
            error: The error message (from ``execution.error_message`` or
                   the raw exception string).

        Returns:
            A ``HealingResult`` with diagnosis, fix, risk, and approval info.
        """
        error_text = error or execution.error_message or ""

        # 1. Root-Cause Analysis
        diagnosis = self._diagnose(error_text)
        logger.info(
            "Healing diagnosis for pipeline %d / exec %d: [%s] %s (conf=%.2f)",
            pipeline.id, execution.id,
            diagnosis.category.value, diagnosis.summary, diagnosis.confidence,
        )

        await self._emit_event(pipeline.id, execution.id, "diagnosis", {
            "category": diagnosis.category.value,
            "summary": diagnosis.summary,
            "confidence": diagnosis.confidence,
        })

        # 2. Generate Fix
        fix = self._propose_fix(diagnosis, pipeline, execution)

        # 3. Assess Risk
        risk = self._assess_risk(diagnosis, fix)
        logger.info("Risk assessment for pipeline %d: %s", pipeline.id, risk.value)

        await self._emit_event(pipeline.id, execution.id, "fix_proposal", {
            "action": fix.action if fix else "none",
            "risk": risk.value,
        })

        # 4. Drive approval or auto-apply
        approval_id: Optional[int] = None
        auto_applied = False

        if risk in (RiskLevel.LOW,):
            # Auto-apply the fix immediately
            try:
                applied = await self._apply_fix(pipeline, execution, fix, diagnosis)
                if applied:
                    auto_applied = True
                    logger.info("Healing: LOW-risk fix auto-applied for pipeline %d", pipeline.id)
                    await self._emit_event(pipeline.id, execution.id, "fix_applied", {
                        "risk": "low",
                        "action": fix.action if fix else "none",
                    })
                else:
                    logger.warning("Healing: fix application returned False for pipeline %d", pipeline.id)
            except Exception as exc:
                logger.error("Healing: fix application failed for pipeline %d: %s", pipeline.id, exc)
                return HealingResult(
                    diagnosis=diagnosis,
                    fix=fix,
                    risk=risk,
                    error=f"Fix application failed: {exc}",
                )

        elif risk == RiskLevel.MEDIUM:
            # Create approval that auto-approves after 5 minutes
            try:
                approval_id = await self._create_approval(
                    pipeline, execution, diagnosis, fix, risk,
                    auto_approve_delay_seconds=300,  # 5 min
                )
                await self._emit_event(pipeline.id, execution.id, "approval_created", {
                    "approval_id": approval_id,
                    "risk": "medium",
                    "auto_approve_in": 300,
                })
            except Exception as exc:
                logger.error("Healing: failed to create MEDIUM approval for pipeline %d: %s", pipeline.id, exc)
                return HealingResult(
                    diagnosis=diagnosis,
                    fix=fix,
                    risk=risk,
                    error=f"Approval creation failed: {exc}",
                )

        else:  # HIGH or CRITICAL
            try:
                approval_id = await self._create_approval(
                    pipeline, execution, diagnosis, fix, risk,
                    auto_approve_delay_seconds=None,  # Requires human approval
                )
                await self._emit_event(pipeline.id, execution.id, "approval_created", {
                    "approval_id": approval_id,
                    "risk": risk.value,
                    "auto_approve": False,
                })
            except Exception as exc:
                logger.error("Healing: failed to create %s approval for pipeline %d: %s",
                              risk.value, pipeline.id, exc)
                return HealingResult(
                    diagnosis=diagnosis,
                    fix=fix,
                    risk=risk,
                    error=f"Approval creation failed: {exc}",
                )

        # 5. Store in RAG memory for future learning
        try:
            self._learn(diagnosis, fix, auto_applied, approval_id)
        except Exception as exc:
            logger.warning("Healing learning step failed (non-fatal): %s", exc)

        return HealingResult(
            diagnosis=diagnosis,
            fix=fix,
            risk=risk,
            approval_id=approval_id,
            auto_applied=auto_applied,
        )

    # ── Step 1: Root-Cause Analysis ────────────────────────────────────

    def _diagnose(self, error_text: str) -> HealingDiagnosis:
        """Match error text against known failure patterns."""
        if not error_text:
            return HealingDiagnosis(
                category=FailureCategory.UNKNOWN,
                summary="No error message available",
                detail="The execution failed but no error text was captured.",
                confidence=0.0,
                error_snippet="",
            )

        best_match: Optional[Tuple[FailureCategory, str, str, float, str]] = None
        best_confidence = 0.0

        for pattern, category, summary, action in FAILURE_PATTERNS:
            match = pattern.search(error_text)
            if match:
                # Confidence: longer, more specific matches score higher
                matched_text = match.group(0)
                specificity = len(matched_text) / max(len(error_text), 1)
                confidence = min(0.5 + specificity * 0.5, 0.98)

                if confidence > best_confidence:
                    best_confidence = confidence
                    best_match = (category, summary, action, confidence, matched_text)

        if best_match is None:
            # No pattern matched — fall back to UNKNOWN
            return HealingDiagnosis(
                category=FailureCategory.UNKNOWN,
                summary="Unrecognised error pattern",
                detail=(
                    f"The error text did not match any known failure category. "
                    f"First 300 chars: {error_text[:300]}"
                ),
                confidence=0.2,
                error_snippet=error_text[:200],
            )

        category, summary, action, confidence, matched_text = best_match

        # Extract affected columns from schema-drift errors
        affected_columns: List[str] = []
        source_tables: List[str] = []

        if category == FailureCategory.SCHEMA_DRIFT:
            col_match = re.search(
                r'column\s+"?(\w+)"?', error_text, re.IGNORECASE
            )
            if col_match:
                affected_columns.append(col_match.group(1))
            table_match = re.search(
                r'(?:table|relation)\s+"?(\w+)"?', error_text, re.IGNORECASE
            )
            if table_match:
                source_tables.append(table_match.group(1))

        detail = (
            f"Pattern '{action}' matched with confidence {confidence:.0%}. "
            f"Error snippet: \"{matched_text}\". "
            f"Full error: {error_text[:400]}"
        )

        return HealingDiagnosis(
            category=category,
            summary=summary,
            detail=detail,
            confidence=round(confidence, 2),
            error_snippet=matched_text,
            affected_columns=affected_columns,
            source_tables=source_tables,
        )

    # ── Step 2: Fix Proposal ───────────────────────────────────────────

    def _propose_fix(
        self,
        diagnosis: HealingDiagnosis,
        pipeline: Pipeline,
        execution: PipelineExecution,
    ) -> Optional[HealingFix]:
        """Generate a fix based on the diagnosis category and action.

        Strategy:
        1. Rule-based: match error against ``FAILURE_PATTERNS`` (fast).
        2. LLM-enhanced: if confidence is low or no rule matched, and
           HuggingFace is available, ask the model to propose a fix.
        3. Fallback: return whatever the rule engine produced.
        """
        # ── 1. Rule-based match ──────────────────────────────────────
        action = next(
            (a for p, _, _, a in FAILURE_PATTERNS if p.search(diagnosis.error_snippet)),
            None,
        )

        # ── 2. LLM-enhanced proposal (when confidence is low) ────────
        if (action is None or diagnosis.confidence < 0.6) and hf_service.is_available():
            try:
                llm_action = self._llm_propose_fix(diagnosis, pipeline)
                if llm_action:
                    logger.info(
                        "LLM proposed fix action '%s' for diagnosis [%s] (rule had: %s)",
                        llm_action, diagnosis.category.value, action,
                    )
                    action = llm_action
            except Exception as exc:
                logger.warning("LLM fix proposal failed, using rule-based: %s", exc)

        if action is None:
            # Fallback: no rule matched and LLM wasn't available or failed
            return None

        return self._generate_fix(action, diagnosis, pipeline, execution)

    def _llm_propose_fix(
        self,
        diagnosis: HealingDiagnosis,
        pipeline: Pipeline,
    ) -> Optional[str]:
        """Ask the HuggingFace LLM to propose a fix action for the diagnosis.

        Returns one of the known action strings (e.g. ``"add_null_handling"``,
        ``"retry_with_backoff"``) or ``None`` if the LLM output can't be parsed.
        """
        known_actions = ", ".join(sorted(set(
            a for _, _, _, a in FAILURE_PATTERNS
        )))

        prompt = (
            f"You are a data-engineering self-healing assistant.\n\n"
            f"A pipeline execution failed with the following diagnosis:\n"
            f"- Category: {diagnosis.category.value}\n"
            f"- Summary: {diagnosis.summary}\n"
            f"- Error snippet: {diagnosis.error_snippet}\n"
            f"- Confidence: {diagnosis.confidence:.0%}\n"
            f"- Pipeline name: {pipeline.name}\n"
            f"- Source: {pipeline.source_type}\n"
            f"- Destination: {pipeline.destination_type}\n\n"
            f"Choose the single best fix action from this list:\n"
            f"{known_actions}\n\n"
            f"Respond with ONLY the action name, nothing else."
        )

        response = hf_service.generate(
            prompt,
            model_name="meta-llama/Llama-3.2-3B-Instruct",
            max_new_tokens=20,
            temperature=0.1,
        )

        if response is None:
            return None

        # Extract just the action word from the response
        response_clean = response.strip().strip("'\"").split()[0].lower()

        # Validate it's a known action
        known_set = {a for _, _, _, a in FAILURE_PATTERNS}
        if response_clean in known_set:
            return response_clean

        # Fuzzy match: partial known action in response
        for known in known_set:
            if known in response_clean or response_clean in known:
                return known

        logger.warning("LLM returned unrecognised action '%s' — ignoring", response_clean)
        return None

    def _generate_fix(
        self,
        action: str,
        diagnosis: HealingDiagnosis,
        pipeline: Pipeline,
        execution: PipelineExecution,
    ) -> HealingFix:
        """Create a structured :class:`HealingFix` for the given action."""

        config = dict(pipeline.config or {})
        config_patch: Optional[Dict[str, Any]] = None
        code_patch: Optional[str] = None

        if action == "update_query":
            # For schema drift: suggest SELECT with explicit column list
            patches: Dict[str, Any] = {}
            if diagnosis.affected_columns:
                patches["affected_columns"] = diagnosis.affected_columns
            if diagnosis.source_tables:
                patches["affected_tables"] = diagnosis.source_tables
            patches["fix_type"] = "refresh_schema"
            config_patch = patches
            description = (
                f"Schema drift detected. Columns {diagnosis.affected_columns} "
                f"may need to be refreshed. Consider re-creating the pipeline "
                f"to discover the current schema."
            )

        elif action == "add_null_handling":
            transformations = config.get("transformations", [])
            if "clean" not in transformations:
                transformations.insert(0, "clean")
            config_patch = {"transformations": transformations}
            description = "Added 'clean' transformation to handle null values."

        elif action == "add_dedup":
            transforms = config.get("transformations", [])
            if "clean" not in transforms:
                transforms.insert(0, "clean")
            config_patch = {"transformations": transforms}
            description = "Added 'clean' transformation to remove duplicates."

        elif action == "add_validation":
            rules = list(config.get("data_quality_rules", []))
            if "no_null_values" not in rules:
                rules.append("no_null_values")
            config_patch = {"data_quality_rules": rules}
            description = "Added data quality validation rules."

        elif action == "add_truncation":
            transforms = list(config.get("transformations", []))
            if "clean" not in transforms:
                transforms.insert(0, "clean")
            config_patch = {"transformations": transforms}
            description = "Added truncation handling via clean transformation."

        elif action == "add_type_cast":
            transforms = list(config.get("transformations", []))
            if "validate" not in transforms:
                transforms.append("validate")
            config_patch = {"transformations": transforms}
            description = "Added type-cast validation step."

        elif action == "add_zero_guard":
            transforms = list(config.get("transformations", []))
            if "validate" not in transforms:
                transforms.append("validate")
            config_patch = {"transformations": transforms}
            description = "Added zero-division guard via validation step."

        elif action == "increase_timeout":
            source_cfg = dict(config.get("source_config", {}))
            source_cfg["timeout_seconds"] = min(
                source_cfg.get("timeout_seconds", 30) * 2, 600
            )
            config_patch = {"source_config": source_cfg}
            description = "Increased source connection timeout."

        elif action == "reduce_batch_size":
            source_cfg = dict(config.get("source_config", {}))
            source_cfg["batch_size"] = max(
                source_cfg.get("batch_size", 10000) // 2, 100
            )
            config_patch = {"source_config": source_cfg}
            description = "Reduced batch size to conserve memory."

        elif action == "retry_with_backoff":
            description = (
                "Connection or deadlock detected. "
                "The pipeline will be retried with exponential backoff."
            )

        elif action == "update_credentials":
            description = (
                "Authentication failed. "
                "Please update the connection credentials in the pipeline settings."
            )

        elif action == "fix_code_error":
            description = (
                "Generated code contains an error. "
                "Consider re-creating the pipeline from the prompt to "
                "regenerate the DAG code."
            )

        elif action == "optimise_query":
            description = (
                "Query execution exceeded time limit. "
                "Consider adding indexes or reducing the data volume."
            )

        elif action == "update_connection_config":
            description = (
                "SSL/TLS configuration issue. "
                "Update the connection string with the correct SSL settings."
            )

        elif action == "check_permissions":
            description = (
                "Permission denied. "
                "Verify the database user has the necessary grants."
            )

        elif action == "increase_storage":
            description = (
                "Disk full on the target system. "
                "Free up space or request a storage increase."
            )

        elif action == "reduce_pool_size":
            source_cfg = dict(config.get("source_config", {}))
            source_cfg["pool_size"] = max(
                source_cfg.get("pool_size", 5) // 2, 1
            )
            config_patch = {"source_config": source_cfg}
            description = "Reduced database connection pool size."

        else:
            description = (
                f"Suggested action '{action}' — review and apply manually."
            )

        return HealingFix(
            action=action,
            description=description,
            config_patch=config_patch,
            code_patch=code_patch,
            message=f"Self-healing: {description}",
        )

    # ── Step 3: Risk Assessment ────────────────────────────────────────

    def _assess_risk(
        self,
        diagnosis: HealingDiagnosis,
        fix: Optional[HealingFix],
    ) -> RiskLevel:
        """Evaluate the risk of applying the proposed fix."""

        # CRITICAL: Schema changes that could lose data
        if diagnosis.category == FailureCategory.SCHEMA_DRIFT:
            if fix and fix.action in ("update_query",):
                return RiskLevel.CRITICAL
            return RiskLevel.HIGH

        # HIGH: Credential changes or connection config updates
        if fix and fix.action in ("update_credentials", "update_connection_config"):
            return RiskLevel.HIGH

        # MEDIUM: Code changes, structural config changes
        if diagnosis.category == FailureCategory.CODE_ERROR:
            return RiskLevel.MEDIUM
        if fix and fix.config_patch and "transformations" in fix.config_patch:
            return RiskLevel.MEDIUM

        # LOW: Performance tuning, retries, timeouts
        if diagnosis.category in (
            FailureCategory.PERFORMANCE,
            FailureCategory.CONNECTION,
        ):
            return RiskLevel.LOW

        if diagnosis.category == FailureCategory.DATA_QUALITY:
            return RiskLevel.LOW

        # Default conservative
        return RiskLevel.MEDIUM

    # ── Step 4: Approval Workflow ──────────────────────────────────────

    async def _get_system_user_id(self, pipeline: Pipeline) -> int:
        """Return a real user ID that satisfies the Approval FK constraint.

        Priority:
        1. Any superuser (admin) from the database
        2. The pipeline's ``user_id`` or ``created_by``
        3. Any active user
        4. Last resort: 1 (the first seeded admin user is always id=1)
        """
        try:
            async with AsyncSessionLocal() as db:
                from sqlalchemy import select

                # 1. Superuser
                result = await db.execute(
                    select(User.id).where(User.is_superuser.is_(True)).limit(1)
                )
                uid = result.scalar_one_or_none()
                if uid:
                    return uid

                # 2. Pipeline owner
                if pipeline.user_id and pipeline.user_id > 0:
                    result = await db.execute(
                        select(User.id).where(User.id == pipeline.user_id)
                    )
                    uid = result.scalar_one_or_none()
                    if uid:
                        return uid

                if pipeline.created_by and pipeline.created_by > 0:
                    result = await db.execute(
                        select(User.id).where(User.id == pipeline.created_by)
                    )
                    uid = result.scalar_one_or_none()
                    if uid:
                        return uid

                # 3. Any active user
                result = await db.execute(
                    select(User.id).where(User.is_active.is_(True)).limit(1)
                )
                uid = result.scalar_one_or_none()
                if uid:
                    return uid

        except Exception as exc:
            logger.warning("Could not look up system user ID: %s", exc)

        return 1  # The admin seed user is always id=1 on a fresh DB

    async def _create_approval(
        self,
        pipeline: Pipeline,
        execution: PipelineExecution,
        diagnosis: HealingDiagnosis,
        fix: Optional[HealingFix],
        risk: RiskLevel,
        auto_approve_delay_seconds: Optional[int] = None,
    ) -> int:
        """
        Create an approval request in the database using the existing
        ``Approval`` model.

        When *auto_approve_delay_seconds* is set, a background task
        auto-approves the request after that many seconds.
        """
        fix_desc = fix.description if fix else "No fix proposed"
        change_detail = json.dumps({
            "pipeline_id": pipeline.id,
            "execution_id": execution.id,
            "diagnosis_category": diagnosis.category.value,
            "diagnosis_summary": diagnosis.summary,
            "fix_action": fix.action if fix else None,
            "fix_config_patch": fix.config_patch if fix else None,
            "fix_code_patch": fix.code_patch if fix else None,
        }, indent=2)

        # Resolve a real user ID for the FK constraint on Approval.created_by
        system_user_id = await self._get_system_user_id(pipeline)

        async with AsyncSessionLocal() as db:
            approval = Approval(
                title=f"Self-healing: {diagnosis.summary}",
                description=(
                    f"Pipeline '{pipeline.name}' (id={pipeline.id}) failed during "
                    f"execution #{execution.id}. The self-healing engine diagnosed "
                    f"the issue as '{diagnosis.category.value}' and proposes the "
                    f"following fix:\n\n{fix_desc}\n\n"
                    f"Risk level: {risk.value}\n"
                    f"Confidence: {diagnosis.confidence:.0%}\n\n"
                    f"Change details:\n{change_detail}"
                ),
                risk=risk,
                created_by=system_user_id,
                created_by_name="Self-Healing Engine",
                change=change_detail,
                resource_type="pipeline",
                resource_name=pipeline.name,
            )
            db.add(approval)
            await db.commit()
            await db.refresh(approval)

            approval_id = approval.id

            # Record the creation action
            action = ApprovalAction(
                approval_id=approval.id,
                action="comment",
                user_id=system_user_id,
                user_name="Self-Healing Engine",
                comment=f"Auto-created healing approval. Risk: {risk.value}. "
                        f"Diagnosis: {diagnosis.summary}",
            )
            db.add(action)
            await db.commit()

        # Schedule auto-approval if applicable
        if auto_approve_delay_seconds is not None and auto_approve_delay_seconds > 0:
            asyncio.ensure_future(
                self._auto_approve_after(approval_id, auto_approve_delay_seconds)
            )

        return approval_id

    async def _auto_approve_after(self, approval_id: int, delay: int) -> None:
        """Auto-approve a pending approval after *delay* seconds.

        Note: This timer is in-memory and will be lost if the process
        restarts before the delay elapses.  For production, use a
        persisted scheduler (e.g. Celery Beat or a DB column for
        scheduled auto-approve time).
        """
        await asyncio.sleep(delay)
        try:
            async with AsyncSessionLocal() as db:
                from sqlalchemy import select
                from app.models.approval import Approval

                result = await db.execute(
                    select(Approval).where(Approval.id == approval_id)
                )
                approval = result.scalar_one_or_none()
                if approval and approval.status == ApprovalStatus.PENDING:
                    approval.status = ApprovalStatus.APPROVED
                    approval.reviewed_by = approval.created_by  # Same user who created it
                    approval.reviewed_by_name = "Self-Healing Engine (auto)"
                    approval.review_comment = (
                        f"Auto-approved after {delay}s timeout."
                    )
                    from datetime import datetime, timezone
                    approval.reviewed_at = datetime.now(timezone.utc)

                    action = ApprovalAction(
                        approval_id=approval.id,
                        action="approve",
                        user_id=approval.created_by,
                        user_name="Self-Healing Engine (auto)",
                        comment="Auto-approved after timeout.",
                    )
                    db.add(action)
                    await db.commit()
                    logger.info(
                        "Approval %d auto-approved after %ds", approval_id, delay
                    )
        except Exception as exc:
            logger.error(
                "Auto-approve failed for approval %d: %s", approval_id, exc
            )

    # ── Step 5: Fix Application ────────────────────────────────────────

    async def _apply_fix(
        self,
        pipeline: Pipeline,
        execution: PipelineExecution,
        fix: Optional[HealingFix],
        diagnosis: HealingDiagnosis,
    ) -> bool:
        """Apply a LOW-risk fix to the pipeline configuration in the database.

        Returns:
            True if the fix was applied successfully.
        """
        if fix is None or (fix.config_patch is None and fix.code_patch is None):
            logger.info("No actionable fix to apply for pipeline %d", pipeline.id)
            return False

        async with AsyncSessionLocal() as db:
            from sqlalchemy import select

            result = await db.execute(
                select(Pipeline).where(Pipeline.id == pipeline.id)
            )
            db_pipeline = result.scalar_one_or_none()
            if db_pipeline is None:
                logger.warning("Pipeline %d not found in DB — cannot apply fix", pipeline.id)
                return False

            # Apply config patch
            if fix.config_patch:
                current_config = dict(db_pipeline.config or {})
                current_config.update(fix.config_patch)
                db_pipeline.config = current_config
                logger.info(
                    "Applied config patch to pipeline %d: %s",
                    pipeline.id,
                    fix.config_patch,
                )

            # Apply code patch
            if fix.code_patch:
                db_pipeline.code = fix.code_patch
                logger.info("Applied code patch to pipeline %d", pipeline.id)

            # Reset status so it can be re-run
            db_pipeline.status = PipelineStatus.DRAFT

            db.add(db_pipeline)
            await db.commit()

        return True

    # ── Step 6: Learning ───────────────────────────────────────────────

    def _learn(
        self,
        diagnosis: HealingDiagnosis,
        fix: Optional[HealingFix],
        auto_applied: bool,
        approval_id: Optional[int],
    ) -> None:
        """Store the diagnosis + fix outcome in RAG memory for future learning."""
        if not rag_memory.is_ready():
            return

        try:
            learning_entry = {
                "category": diagnosis.category.value,
                "error_snippet": diagnosis.error_snippet,
                "summary": diagnosis.summary,
                "fix_action": fix.action if fix else None,
                "fix_description": fix.description if fix else None,
                "auto_applied": auto_applied,
                "approval_id": approval_id,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }
            # Store as a pseudo-pipeline for RAG retrieval
            rag_memory.store_pipeline(
                query=f"healing: {diagnosis.summary}",
                parsed=learning_entry,
                user_id=-1,  # System user
            )
        except Exception as exc:
            logger.warning("RAG learning step failed (non-fatal): %s", exc)

    # ── Helpers ────────────────────────────────────────────────────────

    async def _emit_event(
        self,
        pipeline_id: int,
        execution_id: int,
        event_type: str,
        data: Dict[str, Any],
    ) -> None:
        """Emit a WebSocket event so the frontend can display healing progress."""
        try:
            await manager.broadcast({
                "type": "self_healing",
                "pipeline_id": pipeline_id,
                "execution_id": execution_id,
                "event": event_type,
                "data": data,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })
        except Exception as exc:
            logger.warning("WebSocket emit failed for self-healing event: %s", exc)


# ══════════════════════════════════════════════════════════════════════════
# Module-level singleton
# ══════════════════════════════════════════════════════════════════════════

self_healing_engine = SelfHealingEngine()
